export { isOperationDefinition, } from './isOperationDefinition'
export { operationDefinitions, } from './operationDefinitions'
export { operationName, } from './operationName'
export { operationType, } from './operationType'
export { executableOperationsMap, } from './executableOperationsMap'
export { subscriptionToQuery, } from './subscriptionToQuery'
